import pkg from '../../../../package.json';

/**
 * Site-wide constants: names, external URLs (from `PUBLIC_*` env with local fallbacks) and the
 * metadata of every static page. The OG image route generates one image per entry here plus one
 * per blog post, so every page the layout links to as `og:image` actually exists.
 */
export const SITE_NAME = 'Starterdough';
export const SITE_TAGLINE = 'Build once. Serve anywhere.';
export const SITE_DESCRIPTION =
	'A Bun-native SaaS starter with authentication, an admin surface and internationalisation — served on the web, as a PWA, on desktop, on mobile, or self-hosted on your own server.';

/** Released version, from the root `package.json` — the one place a version is written down. */
export const VERSION: string = pkg.version;

/**
 * Public repository of *this* copy, if there is one: the footer link, "View on GitHub" on the
 * landing page, the changelog's commit history and the contact page's "found a bug". Unset — the
 * default — renders none of them, so nothing ships pointing at somebody else's repository.
 */
export const repoUrl: string | null =
	import.meta.env.PUBLIC_REPO_URL?.trim().replace(/\/+$/, '') || null;

/** Link text for `repoUrl` (`github.com/acme/product`). */
export const repoLabel: string | null = repoUrl?.replace(/^https?:\/\//, '') ?? null;

/**
 * Address shown to visitors who cannot use the contact form (no JavaScript). Optional: unset, the
 * page simply says the form needs JavaScript. This is *not* where the form delivers — that is the
 * API's own `CONTACT_EMAIL`, which never reaches the browser.
 */
export const contactEmail: string | null = import.meta.env.PUBLIC_CONTACT_EMAIL?.trim() || null;

export const appUrl: string = import.meta.env.PUBLIC_APP_URL ?? 'http://localhost:5173';
export const docsUrl: string = import.meta.env.PUBLIC_DOCS_URL ?? 'http://localhost:4322';
export const apiUrl: string = import.meta.env.PUBLIC_API_URL ?? 'http://localhost:3000';

export interface PageMeta {
	/** Route path, e.g. `/features`. */
	path: string;
	/** Key of the generated OG image: `/og/<ogKey>.png`. */
	ogKey: string;
	title: string;
	description: string;
}

export const pages = {
	home: {
		path: '/',
		ogKey: 'index',
		title: 'Starterdough — build once, serve anywhere',
		description: SITE_DESCRIPTION,
	},
	features: {
		path: '/features',
		ogKey: 'features',
		title: 'Features',
		description:
			'Authentication, an admin surface, a frontend platform, PWA, native shells and self-hosting — built once around a single HTTP API.',
	},
	changelog: {
		path: '/changelog',
		ogKey: 'changelog',
		title: 'Changelog',
		description: 'What shipped in Starterdough, release by release.',
	},
	blog: {
		path: '/blog',
		ogKey: 'blog',
		title: 'Blog',
		description: 'Notes on how Starterdough is built and why.',
	},
	contact: {
		path: '/contact',
		ogKey: 'contact',
		title: 'Contact',
		description: 'Ask a question, report a problem or join the waitlist.',
	},
	privacy: {
		path: '/legal/privacy',
		ogKey: 'legal/privacy',
		title: 'Privacy policy',
		description: 'How this deployment of Starterdough handles personal data.',
	},
	terms: {
		path: '/legal/terms',
		ogKey: 'legal/terms',
		title: 'Terms of service',
		description: 'The terms under which this deployment of Starterdough is offered.',
	},
} satisfies Record<string, PageMeta>;

export const staticPages: PageMeta[] = Object.values(pages);

/** `/og/<key>.png` — the image generated by `src/pages/og/[...route].ts` for that key. */
export function ogImagePath(key: string): string {
	return `/og/${key}.png`;
}

/**
 * `astro.config.mjs` always resolves `site` (from `SITE_URL`, or the dev fallback), and refuses a
 * missing or placeholder value on a production build — so pages never need a fallback origin of
 * their own. This turns that invariant into one explicit failure instead of silent `example.com`
 * URLs in a feed or a sitemap.
 */
export function requireSite(site: URL | undefined): URL {
	if (!site) throw new Error('`site` is unset: astro.config.mjs must resolve it from SITE_URL.');
	return site;
}

/** Turns a pathname into the OG image key used above: `/` → `index`, `/blog/x/` → `blog/x`. */
export function ogKeyFor(pathname: string): string {
	const trimmed = pathname.replace(/^\/+|\/+$/g, '');
	return trimmed === '' ? 'index' : trimmed;
}

export function formatDate(date: Date): string {
	return date.toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'short',
		day: 'numeric',
		timeZone: 'UTC',
	});
}
