import { join } from 'node:path';
import { migrate } from 'drizzle-orm/bun-sql/migrator';
import { db, pg } from './client';
import { migrationStatus } from './migrations';

/**
 * Apply pending SQL migrations from ./drizzle (generated by `bun run db:generate`).
 *
 * Rolling deployments start several containers at once and Drizzle's migrator is not
 * concurrency-safe (two runners can apply the same file), so the run holds one advisory lock on a
 * fixed key: the second runner waits for the first, then finds nothing pending. The lock lives on
 * its own reserved connection because the migrator takes others from the pool; Postgres would drop
 * it with the session anyway.
 */
const MIGRATION_LOCK_KEY = 4_021_927_183;

let lock: Awaited<ReturnType<typeof pg.reserve>> | null = null;
try {
	lock = await pg.reserve();
	await lock`select pg_advisory_lock(${MIGRATION_LOCK_KEY})`;
	await migrate(db, { migrationsFolder: join(import.meta.dir, '../drizzle') });
	// Drizzle's migrator compares each file against the *single newest* applied `when`, so a migration
	// whose journal timestamp is older than one already applied — exactly what merging a branch
	// produces — is skipped permanently while `migrate()` still resolves. Verify inside the lock, where
	// nothing else can be applying: anything still pending means a green deploy against a schema the
	// new code does not match.
	const status = await migrationStatus();
	if (status.pending.length > 0) {
		throw new Error(
			`still pending after the run: ${status.pending.join(', ')}. Drizzle skipped them because their journal timestamp is older than the newest applied migration — regenerate them so they sort last, or apply them by hand.`,
		);
	}
	console.log(`✓ migrations applied (${status.applied} of ${status.shipped})`);
} catch (error) {
	// One line, then a non-zero exit: this runs as a deployment step, and a half-applied schema must
	// stop the rollout rather than let the new code start against the old tables.
	console.error(`✗ migration failed: ${error instanceof Error ? error.message : String(error)}`);
	process.exitCode = 1;
} finally {
	if (lock) {
		await lock`select pg_advisory_unlock(${MIGRATION_LOCK_KEY})`.catch(() => {});
		lock.release();
	}
	await pg.close();
}
